-- Pembaruan data HP Kepsek & Operator satuan pendidikan
CREATE TABLE IF NOT EXISTS `pengkinian_data_satuan` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nama_satuan_pendidikan` varchar(200) NOT NULL,
  `nama_kepala_sekolah` varchar(150) NOT NULL,
  `nama_operator` varchar(150) NOT NULL,
  `nomor_hp_kepsek` varchar(30) NOT NULL,
  `nomor_hp_kepsek_norm` varchar(20) DEFAULT NULL,
  `nomor_hp_operator` varchar(30) NOT NULL,
  `nomor_hp_operator_norm` varchar(20) DEFAULT NULL,
  `kode_provinsi` varchar(10) DEFAULT NULL,
  `nama_provinsi` varchar(100) DEFAULT NULL,
  `kode_kabupaten` varchar(10) DEFAULT NULL,
  `nama_kabupaten` varchar(150) DEFAULT NULL,
  `kode_kecamatan` varchar(10) DEFAULT NULL,
  `nama_kecamatan` varchar(150) DEFAULT NULL,
  `kode_kelurahan` varchar(20) DEFAULT NULL,
  `nama_kelurahan` varchar(150) DEFAULT NULL,
  `alamat_detail` text DEFAULT NULL,
  `alamat_lengkap` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_nama_satuan` (`nama_satuan_pendidikan`),
  KEY `idx_kecamatan` (`nama_kecamatan`),
  KEY `idx_hp_kepsek_norm` (`nomor_hp_kepsek_norm`),
  KEY `idx_hp_operator_norm` (`nomor_hp_operator_norm`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
